### ISSUE TITLE
why is server_update set to true by default? 

### ISSUE THREAD

**Issue by ghost** [nexcess/ansible-role-server#145]
https://github.com/nexcess/ansible-role-server/blob/master/defaults/main.yml#L12

Since this role is effectively our base profile why do we default to doing an yum update every run?
I suspect it is due to metaworx but i nearly updated nos due to it.

I find it weird to be here since it isn't an impotent action to perform, even more so that it is a default.

**Comment by clwells** [comment]
Since Ansible is deploy based I typically want this.  That said it's easily overridden if it's not desired.

**Comment by ghost** [comment]
But since we also use it to maintain systems, its seems harmful; nos, r2d2, the mirror systems, openstack, etc. it seems backwards to have to opt-out instead of opt-in since a playbook can be ran multiple times.

**Comment by ChrisOrlando** [comment]
+1, seems dangerous defaulting to system update if we are routinely managing things like firewall rules and minor config updates w/ ansible

**Comment by clwells** [comment]
Will defer to @rfxn
